#############################################################################
# Makefile for building: bin/quiterss
# Generated by qmake (3.1) (Qt 5.15.8)
# Project:  quiterss2.pro
# Template: app
# Command: /usr/lib/qt5/bin/qmake -o Makefile quiterss2.pro
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DAPP_VERSION=\"0.0.1\" -DAPP_REVISION=\"1\" -DAPP_DATE=\"28.07.2017\" -DGANALYTICS_QTQUICK -DRESOURCES_DIR=\"/usr/share/quiterss\" -DQT_NO_DEBUG -DQT_WEBENGINE_LIB -DQT_WEBENGINECORE_LIB -DQT_QUICK_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_QMLMODELS_LIB -DQT_WEBCHANNEL_LIB -DQT_QML_LIB -DQT_NETWORK_LIB -DQT_POSITIONING_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -Wall -Wextra -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -O2 -std=gnu++11 -Wall -Wextra -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -Isrc -Isrc/application -Isrc/common -Isrc/systemtray -Isrc/network -Isrc/webengine -Isrc/3rdparty/qtsingleapplication -Isrc/3rdparty/ganalytics -Itranslations -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWebEngine -I/usr/include/x86_64-linux-gnu/qt5/QtWebEngineCore -I/usr/include/x86_64-linux-gnu/qt5/QtQuick -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtQmlModels -I/usr/include/x86_64-linux-gnu/qt5/QtWebChannel -I/usr/include/x86_64-linux-gnu/qt5/QtQml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtPositioning -I/usr/include/x86_64-linux-gnu/qt5/QtCore -Imoc -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++
QMAKE         = /usr/lib/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/lib/qt5/bin/qmake -install qinstall
QINSTALL_PROGRAM = /usr/lib/qt5/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = quiterss0.0.1.1
DISTDIR = /workspace/obj/quiterss0.0.1.1
LINK          = g++
LFLAGS        = -Wl,-O1 -Wl,-rpath-link,/usr/lib/x86_64-linux-gnu
LIBS          = $(SUBLIBS) /usr/lib/x86_64-linux-gnu/libQt5WebEngine.so /usr/lib/x86_64-linux-gnu/libQt5WebEngineCore.so /usr/lib/x86_64-linux-gnu/libQt5Quick.so /usr/lib/x86_64-linux-gnu/libQt5Widgets.so /usr/lib/x86_64-linux-gnu/libQt5Gui.so /usr/lib/x86_64-linux-gnu/libQt5QmlModels.so /usr/lib/x86_64-linux-gnu/libQt5WebChannel.so /usr/lib/x86_64-linux-gnu/libQt5Qml.so /usr/lib/x86_64-linux-gnu/libQt5Network.so /usr/lib/x86_64-linux-gnu/libQt5Positioning.so /usr/lib/x86_64-linux-gnu/libQt5Core.so -lGL -lpthread   
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = obj/

####### Files

SOURCES       = src/application/application.cpp \
		src/common/common.cpp \
		src/main.cpp \
		src/systemtray/systemtray.cpp \
		src/application/logfile.cpp \
		src/application/settings.cpp \
		src/network/networkmanager.cpp \
		src/webengine/cookiejar.cpp \
		src/webengine/webengine.cpp \
		src/3rdparty/qtsingleapplication/qtsingleapplication.cpp \
		src/3rdparty/qtsingleapplication/qtlocalpeer.cpp \
		src/3rdparty/ganalytics/ganalytics.cpp rcc/qrc_qml.cpp \
		rcc/qrc_images.cpp \
		moc/moc_application.cpp \
		moc/moc_systemtray.cpp \
		moc/moc_networkmanager.cpp \
		moc/moc_cookiejar.cpp \
		moc/moc_webengine.cpp \
		moc/moc_qtsingleapplication.cpp \
		moc/moc_qtlocalpeer.cpp \
		moc/moc_ganalytics.cpp
OBJECTS       = obj/application.o \
		obj/common.o \
		obj/main.o \
		obj/systemtray.o \
		obj/logfile.o \
		obj/settings.o \
		obj/networkmanager.o \
		obj/cookiejar.o \
		obj/webengine.o \
		obj/qtsingleapplication.o \
		obj/qtlocalpeer.o \
		obj/ganalytics.o \
		obj/qrc_qml.o \
		obj/qrc_images.o \
		obj/moc_application.o \
		obj/moc_systemtray.o \
		obj/moc_networkmanager.o \
		obj/moc_cookiejar.o \
		obj/moc_webengine.o \
		obj/moc_qtsingleapplication.o \
		obj/moc_qtlocalpeer.o \
		obj/moc_ganalytics.o
DIST          = CHANGELOG \
		LICENSE \
		AUTHORS \
		INSTALL \
		README.md \
		CONTRIBUTING.md \
		platforms/ios/Info.plist \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_positioning.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_positioningquick.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmlmodels.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webchannel.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webengine.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webenginecore.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webview.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		src/3rdparty/qtsingleapplication/qtsingleapplication.pri \
		src/3rdparty/ganalytics/ganalytics.pri \
		translations/translations.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		quiterss2.pro src/application/application.h \
		src/systemtray/systemtray.h \
		src/application/logfile.h \
		src/application/settings.h \
		src/common/common.h \
		src/network/networkmanager.h \
		src/webengine/cookiejar.h \
		src/webengine/webengine.h \
		src/3rdparty/qtsingleapplication/qtsingleapplication.h \
		src/3rdparty/qtsingleapplication/qtlocalpeer.h \
		src/3rdparty/ganalytics/ganalytics.h src/application/application.cpp \
		src/common/common.cpp \
		src/main.cpp \
		src/systemtray/systemtray.cpp \
		src/application/logfile.cpp \
		src/application/settings.cpp \
		src/network/networkmanager.cpp \
		src/webengine/cookiejar.cpp \
		src/webengine/webengine.cpp \
		src/3rdparty/qtsingleapplication/qtsingleapplication.cpp \
		src/3rdparty/qtsingleapplication/qtlocalpeer.cpp \
		src/3rdparty/ganalytics/ganalytics.cpp
QMAKE_TARGET  = quiterss
DESTDIR       = bin/
TARGET        = bin/quiterss


first: all
####### Build rules

bin/quiterss: bin/translations/quiterss_bg.qm bin/translations/quiterss_de.qm bin/translations/quiterss_fa.qm bin/translations/quiterss_hu.qm bin/translations/quiterss_it.qm bin/translations/quiterss_pt_BR.qm bin/translations/quiterss_ru.qm bin/translations/quiterss_sv.qm bin/translations/quiterss_tr.qm bin/translations/quiterss_zh_TW.qm $(OBJECTS)  
	@test -d bin/ || mkdir -p bin/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: quiterss2.pro /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_positioning.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_positioningquick.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmlmodels.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webchannel.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webengine.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webenginecore.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webview.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		src/3rdparty/qtsingleapplication/qtsingleapplication.pri \
		src/3rdparty/ganalytics/ganalytics.pri \
		translations/translations.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		quiterss2.pro \
		resources/qml.qrc \
		resources/images.qrc
	$(QMAKE) -o Makefile quiterss2.pro
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_positioning.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_positioningquick.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmlmodels.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmlworkerscript.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webchannel.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webengine.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webenginecore.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webenginewidgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webview.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf:
.qmake.stash:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf:
src/3rdparty/qtsingleapplication/qtsingleapplication.pri:
src/3rdparty/ganalytics/ganalytics.pri:
translations/translations.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf:
quiterss2.pro:
resources/qml.qrc:
resources/images.qrc:
qmake: FORCE
	@$(QMAKE) -o Makefile quiterss2.pro

qmake_all: FORCE


all: Makefile bin/quiterss

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents translations/quiterss_bg.ts translations/quiterss_de.ts translations/quiterss_fa.ts translations/quiterss_hu.ts translations/quiterss_it.ts translations/quiterss_pt_BR.ts translations/quiterss_ru.ts translations/quiterss_sv.ts translations/quiterss_tr.ts translations/quiterss_zh_TW.ts $(DISTDIR)/
	$(COPY_FILE) --parents resources/qml.qrc resources/images.qrc $(DISTDIR)/
	$(COPY_FILE) --parents /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents src/application/application.h src/systemtray/systemtray.h src/application/logfile.h src/application/settings.h src/common/common.h src/network/networkmanager.h src/webengine/cookiejar.h src/webengine/webengine.h src/3rdparty/qtsingleapplication/qtsingleapplication.h src/3rdparty/qtsingleapplication/qtlocalpeer.h src/3rdparty/ganalytics/ganalytics.h $(DISTDIR)/
	$(COPY_FILE) --parents src/application/application.cpp src/common/common.cpp src/main.cpp src/systemtray/systemtray.cpp src/application/logfile.cpp src/application/settings.cpp src/network/networkmanager.cpp src/webengine/cookiejar.cpp src/webengine/webengine.cpp src/3rdparty/qtsingleapplication/qtsingleapplication.cpp src/3rdparty/qtsingleapplication/qtlocalpeer.cpp src/3rdparty/ganalytics/ganalytics.cpp $(DISTDIR)/
	$(COPY_FILE) --parents translations/quiterss_bg.ts translations/quiterss_de.ts translations/quiterss_fa.ts translations/quiterss_hu.ts translations/quiterss_it.ts translations/quiterss_pt_BR.ts translations/quiterss_ru.ts translations/quiterss_sv.ts translations/quiterss_tr.ts translations/quiterss_zh_TW.ts $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_updateqm_make_all: bin/translations/quiterss_bg.qm bin/translations/quiterss_de.qm bin/translations/quiterss_fa.qm bin/translations/quiterss_hu.qm bin/translations/quiterss_it.qm bin/translations/quiterss_pt_BR.qm bin/translations/quiterss_ru.qm bin/translations/quiterss_sv.qm bin/translations/quiterss_tr.qm bin/translations/quiterss_zh_TW.qm
compiler_updateqm_clean:
	-$(DEL_FILE) bin/translations/quiterss_bg.qm bin/translations/quiterss_de.qm bin/translations/quiterss_fa.qm bin/translations/quiterss_hu.qm bin/translations/quiterss_it.qm bin/translations/quiterss_pt_BR.qm bin/translations/quiterss_ru.qm bin/translations/quiterss_sv.qm bin/translations/quiterss_tr.qm bin/translations/quiterss_zh_TW.qm
bin/translations/quiterss_bg.qm: translations/quiterss_bg.ts
	/usr/lib/qt5/bin/lrelease translations/quiterss_bg.ts -qm /workspace/bin/translations/quiterss_bg.qm

bin/translations/quiterss_de.qm: translations/quiterss_de.ts
	/usr/lib/qt5/bin/lrelease translations/quiterss_de.ts -qm /workspace/bin/translations/quiterss_de.qm

bin/translations/quiterss_fa.qm: translations/quiterss_fa.ts
	/usr/lib/qt5/bin/lrelease translations/quiterss_fa.ts -qm /workspace/bin/translations/quiterss_fa.qm

bin/translations/quiterss_hu.qm: translations/quiterss_hu.ts
	/usr/lib/qt5/bin/lrelease translations/quiterss_hu.ts -qm /workspace/bin/translations/quiterss_hu.qm

bin/translations/quiterss_it.qm: translations/quiterss_it.ts
	/usr/lib/qt5/bin/lrelease translations/quiterss_it.ts -qm /workspace/bin/translations/quiterss_it.qm

bin/translations/quiterss_pt_BR.qm: translations/quiterss_pt_BR.ts
	/usr/lib/qt5/bin/lrelease translations/quiterss_pt_BR.ts -qm /workspace/bin/translations/quiterss_pt_BR.qm

bin/translations/quiterss_ru.qm: translations/quiterss_ru.ts
	/usr/lib/qt5/bin/lrelease translations/quiterss_ru.ts -qm /workspace/bin/translations/quiterss_ru.qm

bin/translations/quiterss_sv.qm: translations/quiterss_sv.ts
	/usr/lib/qt5/bin/lrelease translations/quiterss_sv.ts -qm /workspace/bin/translations/quiterss_sv.qm

bin/translations/quiterss_tr.qm: translations/quiterss_tr.ts
	/usr/lib/qt5/bin/lrelease translations/quiterss_tr.ts -qm /workspace/bin/translations/quiterss_tr.qm

bin/translations/quiterss_zh_TW.qm: translations/quiterss_zh_TW.ts
	/usr/lib/qt5/bin/lrelease translations/quiterss_zh_TW.ts -qm /workspace/bin/translations/quiterss_zh_TW.qm

compiler_rcc_make_all: rcc/qrc_qml.cpp rcc/qrc_images.cpp
compiler_rcc_clean:
	-$(DEL_FILE) rcc/qrc_qml.cpp rcc/qrc_images.cpp
rcc/qrc_qml.cpp: resources/qml.qrc \
		/usr/lib/qt5/bin/rcc \
		resources/qml/SystemTrayIcon.qml \
		resources/qml/ClosingWindow.qml \
		resources/qml/WebView.qml \
		resources/qml/TabViewApp.qml \
		resources/qml/AuthenticationDialog.qml \
		resources/qml/SplashScreen.qml \
		resources/qml/mainwindow.qml \
		resources/qml/IconTab.qml \
		resources/qml/+webview/WebView.qml \
		resources/qml/+mobile/mainwindow.qml
	/usr/lib/qt5/bin/rcc -name qml resources/qml.qrc -o rcc/qrc_qml.cpp

rcc/qrc_images.cpp: resources/images.qrc \
		/usr/lib/qt5/bin/rcc \
		resources/images/tray-icon.png \
		resources/images/feed-icon.png \
		resources/images/quiterss.png \
		resources/images/splash-screen.png \
		resources/images/updateAllFeeds.png
	/usr/lib/qt5/bin/rcc -name images resources/images.qrc -o rcc/qrc_images.cpp

compiler_moc_predefs_make_all: moc/moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc/moc_predefs.h
moc/moc_predefs.h: /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp
	g++ -pipe -O2 -std=gnu++11 -Wall -Wextra -dM -E -o moc/moc_predefs.h /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc/moc_application.cpp moc/moc_systemtray.cpp moc/moc_networkmanager.cpp moc/moc_cookiejar.cpp moc/moc_webengine.cpp moc/moc_qtsingleapplication.cpp moc/moc_qtlocalpeer.cpp moc/moc_ganalytics.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc/moc_application.cpp moc/moc_systemtray.cpp moc/moc_networkmanager.cpp moc/moc_cookiejar.cpp moc/moc_webengine.cpp moc/moc_qtsingleapplication.cpp moc/moc_qtlocalpeer.cpp moc/moc_ganalytics.cpp
moc/moc_application.cpp: src/application/application.h \
		src/3rdparty/qtsingleapplication/qtsingleapplication.h \
		src/common/common.h \
		src/application/settings.h \
		src/3rdparty/ganalytics/ganalytics.h \
		src/network/networkmanager.h \
		src/webengine/webengine.h \
		src/webengine/cookiejar.h \
		moc/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /workspace/moc/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/workspace -I/workspace/src -I/workspace/src/application -I/workspace/src/common -I/workspace/src/systemtray -I/workspace/src/network -I/workspace/src/webengine -I/workspace/src/3rdparty/qtsingleapplication -I/workspace/src/3rdparty/ganalytics -I/workspace/translations -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWebEngine -I/usr/include/x86_64-linux-gnu/qt5/QtWebEngineCore -I/usr/include/x86_64-linux-gnu/qt5/QtQuick -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtQmlModels -I/usr/include/x86_64-linux-gnu/qt5/QtWebChannel -I/usr/include/x86_64-linux-gnu/qt5/QtQml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtPositioning -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/12 -I/usr/include/x86_64-linux-gnu/c++/12 -I/usr/include/c++/12/backward -I/usr/lib/gcc/x86_64-linux-gnu/12/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/application/application.h -o moc/moc_application.cpp

moc/moc_systemtray.cpp: src/systemtray/systemtray.h \
		moc/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /workspace/moc/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/workspace -I/workspace/src -I/workspace/src/application -I/workspace/src/common -I/workspace/src/systemtray -I/workspace/src/network -I/workspace/src/webengine -I/workspace/src/3rdparty/qtsingleapplication -I/workspace/src/3rdparty/ganalytics -I/workspace/translations -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWebEngine -I/usr/include/x86_64-linux-gnu/qt5/QtWebEngineCore -I/usr/include/x86_64-linux-gnu/qt5/QtQuick -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtQmlModels -I/usr/include/x86_64-linux-gnu/qt5/QtWebChannel -I/usr/include/x86_64-linux-gnu/qt5/QtQml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtPositioning -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/12 -I/usr/include/x86_64-linux-gnu/c++/12 -I/usr/include/c++/12/backward -I/usr/lib/gcc/x86_64-linux-gnu/12/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/systemtray/systemtray.h -o moc/moc_systemtray.cpp

moc/moc_networkmanager.cpp: src/network/networkmanager.h \
		moc/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /workspace/moc/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/workspace -I/workspace/src -I/workspace/src/application -I/workspace/src/common -I/workspace/src/systemtray -I/workspace/src/network -I/workspace/src/webengine -I/workspace/src/3rdparty/qtsingleapplication -I/workspace/src/3rdparty/ganalytics -I/workspace/translations -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWebEngine -I/usr/include/x86_64-linux-gnu/qt5/QtWebEngineCore -I/usr/include/x86_64-linux-gnu/qt5/QtQuick -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtQmlModels -I/usr/include/x86_64-linux-gnu/qt5/QtWebChannel -I/usr/include/x86_64-linux-gnu/qt5/QtQml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtPositioning -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/12 -I/usr/include/x86_64-linux-gnu/c++/12 -I/usr/include/c++/12/backward -I/usr/lib/gcc/x86_64-linux-gnu/12/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/network/networkmanager.h -o moc/moc_networkmanager.cpp

moc/moc_cookiejar.cpp: src/webengine/cookiejar.h \
		moc/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /workspace/moc/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/workspace -I/workspace/src -I/workspace/src/application -I/workspace/src/common -I/workspace/src/systemtray -I/workspace/src/network -I/workspace/src/webengine -I/workspace/src/3rdparty/qtsingleapplication -I/workspace/src/3rdparty/ganalytics -I/workspace/translations -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWebEngine -I/usr/include/x86_64-linux-gnu/qt5/QtWebEngineCore -I/usr/include/x86_64-linux-gnu/qt5/QtQuick -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtQmlModels -I/usr/include/x86_64-linux-gnu/qt5/QtWebChannel -I/usr/include/x86_64-linux-gnu/qt5/QtQml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtPositioning -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/12 -I/usr/include/x86_64-linux-gnu/c++/12 -I/usr/include/c++/12/backward -I/usr/lib/gcc/x86_64-linux-gnu/12/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/webengine/cookiejar.h -o moc/moc_cookiejar.cpp

moc/moc_webengine.cpp: src/webengine/webengine.h \
		src/webengine/cookiejar.h \
		moc/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /workspace/moc/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/workspace -I/workspace/src -I/workspace/src/application -I/workspace/src/common -I/workspace/src/systemtray -I/workspace/src/network -I/workspace/src/webengine -I/workspace/src/3rdparty/qtsingleapplication -I/workspace/src/3rdparty/ganalytics -I/workspace/translations -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWebEngine -I/usr/include/x86_64-linux-gnu/qt5/QtWebEngineCore -I/usr/include/x86_64-linux-gnu/qt5/QtQuick -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtQmlModels -I/usr/include/x86_64-linux-gnu/qt5/QtWebChannel -I/usr/include/x86_64-linux-gnu/qt5/QtQml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtPositioning -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/12 -I/usr/include/x86_64-linux-gnu/c++/12 -I/usr/include/c++/12/backward -I/usr/lib/gcc/x86_64-linux-gnu/12/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/webengine/webengine.h -o moc/moc_webengine.cpp

moc/moc_qtsingleapplication.cpp: src/3rdparty/qtsingleapplication/qtsingleapplication.h \
		moc/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /workspace/moc/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/workspace -I/workspace/src -I/workspace/src/application -I/workspace/src/common -I/workspace/src/systemtray -I/workspace/src/network -I/workspace/src/webengine -I/workspace/src/3rdparty/qtsingleapplication -I/workspace/src/3rdparty/ganalytics -I/workspace/translations -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWebEngine -I/usr/include/x86_64-linux-gnu/qt5/QtWebEngineCore -I/usr/include/x86_64-linux-gnu/qt5/QtQuick -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtQmlModels -I/usr/include/x86_64-linux-gnu/qt5/QtWebChannel -I/usr/include/x86_64-linux-gnu/qt5/QtQml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtPositioning -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/12 -I/usr/include/x86_64-linux-gnu/c++/12 -I/usr/include/c++/12/backward -I/usr/lib/gcc/x86_64-linux-gnu/12/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/3rdparty/qtsingleapplication/qtsingleapplication.h -o moc/moc_qtsingleapplication.cpp

moc/moc_qtlocalpeer.cpp: src/3rdparty/qtsingleapplication/qtlocalpeer.h \
		src/3rdparty/qtsingleapplication/qtlockedfile.h \
		moc/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /workspace/moc/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/workspace -I/workspace/src -I/workspace/src/application -I/workspace/src/common -I/workspace/src/systemtray -I/workspace/src/network -I/workspace/src/webengine -I/workspace/src/3rdparty/qtsingleapplication -I/workspace/src/3rdparty/ganalytics -I/workspace/translations -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWebEngine -I/usr/include/x86_64-linux-gnu/qt5/QtWebEngineCore -I/usr/include/x86_64-linux-gnu/qt5/QtQuick -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtQmlModels -I/usr/include/x86_64-linux-gnu/qt5/QtWebChannel -I/usr/include/x86_64-linux-gnu/qt5/QtQml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtPositioning -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/12 -I/usr/include/x86_64-linux-gnu/c++/12 -I/usr/include/c++/12/backward -I/usr/lib/gcc/x86_64-linux-gnu/12/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/3rdparty/qtsingleapplication/qtlocalpeer.h -o moc/moc_qtlocalpeer.cpp

moc/moc_ganalytics.cpp: src/3rdparty/ganalytics/ganalytics.h \
		moc/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /workspace/moc/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/workspace -I/workspace/src -I/workspace/src/application -I/workspace/src/common -I/workspace/src/systemtray -I/workspace/src/network -I/workspace/src/webengine -I/workspace/src/3rdparty/qtsingleapplication -I/workspace/src/3rdparty/ganalytics -I/workspace/translations -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWebEngine -I/usr/include/x86_64-linux-gnu/qt5/QtWebEngineCore -I/usr/include/x86_64-linux-gnu/qt5/QtQuick -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtQmlModels -I/usr/include/x86_64-linux-gnu/qt5/QtWebChannel -I/usr/include/x86_64-linux-gnu/qt5/QtQml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtPositioning -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/12 -I/usr/include/x86_64-linux-gnu/c++/12 -I/usr/include/c++/12/backward -I/usr/lib/gcc/x86_64-linux-gnu/12/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/3rdparty/ganalytics/ganalytics.h -o moc/moc_ganalytics.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_updateqm_clean compiler_rcc_clean compiler_moc_predefs_clean compiler_moc_header_clean 

####### Compile

obj/application.o: src/application/application.cpp src/application/application.h \
		src/3rdparty/qtsingleapplication/qtsingleapplication.h \
		src/common/common.h \
		src/application/settings.h \
		src/3rdparty/ganalytics/ganalytics.h \
		src/network/networkmanager.h \
		src/webengine/webengine.h \
		src/webengine/cookiejar.h \
		src/systemtray/systemtray.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/application.o src/application/application.cpp

obj/common.o: src/common/common.cpp src/common/common.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/common.o src/common/common.cpp

obj/main.o: src/main.cpp src/application/application.h \
		src/3rdparty/qtsingleapplication/qtsingleapplication.h \
		src/common/common.h \
		src/application/settings.h \
		src/3rdparty/ganalytics/ganalytics.h \
		src/network/networkmanager.h \
		src/webengine/webengine.h \
		src/webengine/cookiejar.h \
		src/application/logfile.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/main.o src/main.cpp

obj/systemtray.o: src/systemtray/systemtray.cpp src/systemtray/systemtray.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/systemtray.o src/systemtray/systemtray.cpp

obj/logfile.o: src/application/logfile.cpp src/application/logfile.h \
		src/application/application.h \
		src/3rdparty/qtsingleapplication/qtsingleapplication.h \
		src/common/common.h \
		src/application/settings.h \
		src/3rdparty/ganalytics/ganalytics.h \
		src/network/networkmanager.h \
		src/webengine/webengine.h \
		src/webengine/cookiejar.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/logfile.o src/application/logfile.cpp

obj/settings.o: src/application/settings.cpp src/application/settings.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/settings.o src/application/settings.cpp

obj/networkmanager.o: src/network/networkmanager.cpp src/network/networkmanager.h \
		src/application/application.h \
		src/3rdparty/qtsingleapplication/qtsingleapplication.h \
		src/common/common.h \
		src/application/settings.h \
		src/3rdparty/ganalytics/ganalytics.h \
		src/webengine/webengine.h \
		src/webengine/cookiejar.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/networkmanager.o src/network/networkmanager.cpp

obj/cookiejar.o: src/webengine/cookiejar.cpp src/webengine/cookiejar.h \
		src/application/application.h \
		src/3rdparty/qtsingleapplication/qtsingleapplication.h \
		src/common/common.h \
		src/application/settings.h \
		src/3rdparty/ganalytics/ganalytics.h \
		src/network/networkmanager.h \
		src/webengine/webengine.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/cookiejar.o src/webengine/cookiejar.cpp

obj/webengine.o: src/webengine/webengine.cpp src/webengine/webengine.h \
		src/webengine/cookiejar.h \
		src/application/application.h \
		src/3rdparty/qtsingleapplication/qtsingleapplication.h \
		src/common/common.h \
		src/application/settings.h \
		src/3rdparty/ganalytics/ganalytics.h \
		src/network/networkmanager.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/webengine.o src/webengine/webengine.cpp

obj/qtsingleapplication.o: src/3rdparty/qtsingleapplication/qtsingleapplication.cpp src/3rdparty/qtsingleapplication/qtsingleapplication.h \
		src/3rdparty/qtsingleapplication/qtlocalpeer.h \
		src/3rdparty/qtsingleapplication/qtlockedfile.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/qtsingleapplication.o src/3rdparty/qtsingleapplication/qtsingleapplication.cpp

obj/qtlocalpeer.o: src/3rdparty/qtsingleapplication/qtlocalpeer.cpp src/3rdparty/qtsingleapplication/qtlocalpeer.h \
		src/3rdparty/qtsingleapplication/qtlockedfile.h \
		src/3rdparty/qtsingleapplication/qtlockedfile.cpp \
		src/3rdparty/qtsingleapplication/qtlockedfile_win.cpp \
		src/3rdparty/qtsingleapplication/qtlockedfile_unix.cpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/qtlocalpeer.o src/3rdparty/qtsingleapplication/qtlocalpeer.cpp

obj/ganalytics.o: src/3rdparty/ganalytics/ganalytics.cpp src/3rdparty/ganalytics/ganalytics.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/ganalytics.o src/3rdparty/ganalytics/ganalytics.cpp

obj/qrc_qml.o: rcc/qrc_qml.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/qrc_qml.o rcc/qrc_qml.cpp

obj/qrc_images.o: rcc/qrc_images.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/qrc_images.o rcc/qrc_images.cpp

obj/moc_application.o: moc/moc_application.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_application.o moc/moc_application.cpp

obj/moc_systemtray.o: moc/moc_systemtray.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_systemtray.o moc/moc_systemtray.cpp

obj/moc_networkmanager.o: moc/moc_networkmanager.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_networkmanager.o moc/moc_networkmanager.cpp

obj/moc_cookiejar.o: moc/moc_cookiejar.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_cookiejar.o moc/moc_cookiejar.cpp

obj/moc_webengine.o: moc/moc_webengine.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_webengine.o moc/moc_webengine.cpp

obj/moc_qtsingleapplication.o: moc/moc_qtsingleapplication.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_qtsingleapplication.o moc/moc_qtsingleapplication.cpp

obj/moc_qtlocalpeer.o: moc/moc_qtlocalpeer.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_qtlocalpeer.o moc/moc_qtlocalpeer.cpp

obj/moc_ganalytics.o: moc/moc_ganalytics.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_ganalytics.o moc/moc_ganalytics.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/usr/bin || mkdir -p $(INSTALL_ROOT)/usr/bin
	$(QINSTALL_PROGRAM) bin/$(QMAKE_TARGET) $(INSTALL_ROOT)/usr/bin/$(QMAKE_TARGET)
	-$(STRIP) $(INSTALL_ROOT)/usr/bin/$(QMAKE_TARGET)

uninstall_target: FORCE
	-$(DEL_FILE) $(INSTALL_ROOT)/usr/bin/$(QMAKE_TARGET)
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/bin/ 


install_target1: first FORCE
	@test -d $(INSTALL_ROOT)/usr/share/applications || mkdir -p $(INSTALL_ROOT)/usr/share/applications
	$(QINSTALL) /workspace/platforms/linux/quiterss.desktop $(INSTALL_ROOT)/usr/share/applications/quiterss.desktop

uninstall_target1: FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/applications/quiterss.desktop
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/share/applications/ 


install_translations: first FORCE
	@test -d $(INSTALL_ROOT)/usr/share/quiterss || mkdir -p $(INSTALL_ROOT)/usr/share/quiterss
	$(QINSTALL) /workspace/bin/translations $(INSTALL_ROOT)/usr/share/quiterss/translations

uninstall_translations: FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/quiterss/translations
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/share/quiterss/ 


install_sound: first FORCE
	@test -d $(INSTALL_ROOT)/usr/share/quiterss || mkdir -p $(INSTALL_ROOT)/usr/share/quiterss
	$(QINSTALL) /workspace/resources/sound $(INSTALL_ROOT)/usr/share/quiterss/sound

uninstall_sound: FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/quiterss/sound
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/share/quiterss/ 


install: install_target install_target1 install_translations install_sound  FORCE

uninstall: uninstall_target uninstall_target1 uninstall_translations uninstall_sound  FORCE

FORCE:

